sudo: required
services:
  - docker

language: generic 
before_install:
  - docker build -f Dockerfile.dev -t wicochandra/udemy-docker-react .

script:
  - docker run -e CI=true wicochandra/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "udemy-docker-react-2"
  env: "Udemydockerreact2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-280037490921"
  bucket_path: "udemy-docker-react-2"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master